// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'store/db/entity/gallery_history.dart';
import 'store/db/entity/nh_tag.dart';
import 'store/db/entity/tag_translate.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8148422562123602304),
    name: 'GalleryHistory',
    lastPropertyId: const obx_int.IdUid(10, 7705130199042705259),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7698275708904361871),
        name: 'gid',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2154694698420025041),
        name: 'mediaId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8365371974194161140),
        name: 'csrfToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4898070901466572546),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5374478938713432179),
        name: 'japaneseTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4049799484638807601),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1030964036804902811),
        name: 'thumbUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5495483508217161989),
        name: 'coverImgHeight',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5602857501507058751),
        name: 'coverImgWidth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7705130199042705259),
        name: 'lastReadTime',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 6591030224407181517),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5347704772409439203),
    name: 'NhTag',
    lastPropertyId: const obx_int.IdUid(6, 7151685249640325339),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5812677314512905427),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5044136010578704901),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 360083855985954000),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6620928045959323518),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 6816027783753901673),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6145422200010693371),
        name: 'translateName',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3221120701071853860),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3740966359783841500),
        name: 'count',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7151685249640325339),
        name: 'lastUseTime',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 6250311997086369052),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4614819919768626068),
    name: 'TagTranslate',
    lastPropertyId: const obx_int.IdUid(7, 5935329526227981884),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4796013884339722270),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5709710560560102678),
        name: 'namespace',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 5273092115694794574),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1803132018018336105),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 8423340687474749211),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 433530849273239227),
        name: 'translateName',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 6644567957832918634),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1723847528773238890),
        name: 'intro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1013948185672778140),
        name: 'links',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5935329526227981884),
        name: 'lastUseTime',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(9, 6175019048317779675),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 4614819919768626068),
    lastIndexId: const obx_int.IdUid(9, 6175019048317779675),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GalleryHistory: obx_int.EntityDefinition<GalleryHistory>(
      model: _entities[0],
      toOneRelations: (GalleryHistory object) => [],
      toManyRelations: (GalleryHistory object) => {},
      getId: (GalleryHistory object) => object.gid,
      setId: (GalleryHistory object, int id) {
        object.gid = id;
      },
      objectToFB: (GalleryHistory object, fb.Builder fbb) {
        final mediaIdOffset = object.mediaId == null
            ? null
            : fbb.writeString(object.mediaId!);
        final csrfTokenOffset = object.csrfToken == null
            ? null
            : fbb.writeString(object.csrfToken!);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final japaneseTitleOffset = object.japaneseTitle == null
            ? null
            : fbb.writeString(object.japaneseTitle!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final thumbUrlOffset = object.thumbUrl == null
            ? null
            : fbb.writeString(object.thumbUrl!);
        fbb.startTable(11);
        fbb.addInt64(0, object.gid);
        fbb.addOffset(1, mediaIdOffset);
        fbb.addOffset(2, csrfTokenOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, japaneseTitleOffset);
        fbb.addOffset(5, urlOffset);
        fbb.addOffset(6, thumbUrlOffset);
        fbb.addInt64(7, object.coverImgHeight);
        fbb.addInt64(8, object.coverImgWidth);
        fbb.addInt64(9, object.lastReadTime);
        fbb.finish(fbb.endTable());
        return object.gid;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final gidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final mediaIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final csrfTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final japaneseTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final thumbUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final coverImgHeightParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final coverImgWidthParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final lastReadTimeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final object = GalleryHistory(
          gid: gidParam,
          mediaId: mediaIdParam,
          csrfToken: csrfTokenParam,
          title: titleParam,
          japaneseTitle: japaneseTitleParam,
          url: urlParam,
          thumbUrl: thumbUrlParam,
          coverImgHeight: coverImgHeightParam,
          coverImgWidth: coverImgWidthParam,
          lastReadTime: lastReadTimeParam,
        );

        return object;
      },
    ),
    NhTag: obx_int.EntityDefinition<NhTag>(
      model: _entities[1],
      toOneRelations: (NhTag object) => [],
      toManyRelations: (NhTag object) => {},
      getId: (NhTag object) => object.id,
      setId: (NhTag object, int id) {
        object.id = id;
      },
      objectToFB: (NhTag object, fb.Builder fbb) {
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final translateNameOffset = object.translateName == null
            ? null
            : fbb.writeString(object.translateName!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, translateNameOffset);
        fbb.addInt64(4, object.count);
        fbb.addInt64(5, object.lastUseTime);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final countParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final lastUseTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final translateNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = NhTag(
          id: idParam,
          name: nameParam,
          count: countParam,
          type: typeParam,
          lastUseTime: lastUseTimeParam,
          translateName: translateNameParam,
        );

        return object;
      },
    ),
    TagTranslate: obx_int.EntityDefinition<TagTranslate>(
      model: _entities[2],
      toOneRelations: (TagTranslate object) => [],
      toManyRelations: (TagTranslate object) => {},
      getId: (TagTranslate object) => object.id,
      setId: (TagTranslate object, int id) {
        object.id = id;
      },
      objectToFB: (TagTranslate object, fb.Builder fbb) {
        final namespaceOffset = fbb.writeString(object.namespace);
        final nameOffset = fbb.writeString(object.name);
        final translateNameOffset = object.translateName == null
            ? null
            : fbb.writeString(object.translateName!);
        final introOffset = object.intro == null
            ? null
            : fbb.writeString(object.intro!);
        final linksOffset = object.links == null
            ? null
            : fbb.writeString(object.links!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, namespaceOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, translateNameOffset);
        fbb.addOffset(4, introOffset);
        fbb.addOffset(5, linksOffset);
        fbb.addInt64(6, object.lastUseTime);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final namespaceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final translateNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final introParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final linksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final lastUseTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = TagTranslate(
          namespace: namespaceParam,
          name: nameParam,
          translateName: translateNameParam,
          intro: introParam,
          links: linksParam,
          lastUseTime: lastUseTimeParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GalleryHistory] entity fields to define ObjectBox queries.
class GalleryHistory_ {
  /// See [GalleryHistory.gid].
  static final gid = obx.QueryIntegerProperty<GalleryHistory>(
    _entities[0].properties[0],
  );

  /// See [GalleryHistory.mediaId].
  static final mediaId = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[1],
  );

  /// See [GalleryHistory.csrfToken].
  static final csrfToken = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[2],
  );

  /// See [GalleryHistory.title].
  static final title = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[3],
  );

  /// See [GalleryHistory.japaneseTitle].
  static final japaneseTitle = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[4],
  );

  /// See [GalleryHistory.url].
  static final url = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[5],
  );

  /// See [GalleryHistory.thumbUrl].
  static final thumbUrl = obx.QueryStringProperty<GalleryHistory>(
    _entities[0].properties[6],
  );

  /// See [GalleryHistory.coverImgHeight].
  static final coverImgHeight = obx.QueryIntegerProperty<GalleryHistory>(
    _entities[0].properties[7],
  );

  /// See [GalleryHistory.coverImgWidth].
  static final coverImgWidth = obx.QueryIntegerProperty<GalleryHistory>(
    _entities[0].properties[8],
  );

  /// See [GalleryHistory.lastReadTime].
  static final lastReadTime = obx.QueryIntegerProperty<GalleryHistory>(
    _entities[0].properties[9],
  );
}

/// [NhTag] entity fields to define ObjectBox queries.
class NhTag_ {
  /// See [NhTag.id].
  static final id = obx.QueryIntegerProperty<NhTag>(_entities[1].properties[0]);

  /// See [NhTag.type].
  static final type = obx.QueryStringProperty<NhTag>(
    _entities[1].properties[1],
  );

  /// See [NhTag.name].
  static final name = obx.QueryStringProperty<NhTag>(
    _entities[1].properties[2],
  );

  /// See [NhTag.translateName].
  static final translateName = obx.QueryStringProperty<NhTag>(
    _entities[1].properties[3],
  );

  /// See [NhTag.count].
  static final count = obx.QueryIntegerProperty<NhTag>(
    _entities[1].properties[4],
  );

  /// See [NhTag.lastUseTime].
  static final lastUseTime = obx.QueryIntegerProperty<NhTag>(
    _entities[1].properties[5],
  );
}

/// [TagTranslate] entity fields to define ObjectBox queries.
class TagTranslate_ {
  /// See [TagTranslate.id].
  static final id = obx.QueryIntegerProperty<TagTranslate>(
    _entities[2].properties[0],
  );

  /// See [TagTranslate.namespace].
  static final namespace = obx.QueryStringProperty<TagTranslate>(
    _entities[2].properties[1],
  );

  /// See [TagTranslate.name].
  static final name = obx.QueryStringProperty<TagTranslate>(
    _entities[2].properties[2],
  );

  /// See [TagTranslate.translateName].
  static final translateName = obx.QueryStringProperty<TagTranslate>(
    _entities[2].properties[3],
  );

  /// See [TagTranslate.intro].
  static final intro = obx.QueryStringProperty<TagTranslate>(
    _entities[2].properties[4],
  );

  /// See [TagTranslate.links].
  static final links = obx.QueryStringProperty<TagTranslate>(
    _entities[2].properties[5],
  );

  /// See [TagTranslate.lastUseTime].
  static final lastUseTime = obx.QueryIntegerProperty<TagTranslate>(
    _entities[2].properties[6],
  );
}
